{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{endpoint=\"get\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"put\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"post\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"delete\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "users_total{users=\"users\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Authentications / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(authentication_total{result=\"successful\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(authentication_total{result=\"failed\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_total{system=\"cpuUsage\", source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_total{system=\"memoryUsage\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Purchases / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizzas_total{metric=\"pizzasSold\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizzas_total{metric=\"failedCreations\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "pizzas_total{metric=\"revenue\", source=\"jwt-pizza-service\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(latency_total{latency=\"http\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(latency_total{latency=\"pizza\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza latency"
    }
   ]
  }
 ]
}